const CONFIG = {
    titleWeb: "nhamnham",
    introTitle: 'chip',
    introDesc: `hiiii gaaaaaaaa`,
    btnIntro: '^^nham^^',
    title: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    desc: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'ieu khum',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'mot ang kem hoq:3',
    btnAccept: 'Okiiiii lun:333',
    messLink: 'https://duonggiabao123123.github.io/Confess-Crush/',
}
