const CONFIG = {
    titleWeb: "nhamnham",
    introTitle: 'chip',
    introDesc: `hiiii gaaaaaaaa`,
    btnIntro: '^^nham^^',
    title: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    desc: 'thich kao khum :<',
    btnYes: 'Thích lắm :3',
    btnNo: 'khum:<',
    question: 'ieu khum',
    btnReply: 'Gửi cho bạn <3',
    reply: 'khum ieu cum~ fai ieu',
    mess: '=)))))))',
    messDesc: 'mot ang kem hoq:3',
    btnAccept: 'Okiiiii lun:333',
    messLink: 'https://www.facebook.com/profile.php?id=100054855643542',
}
